"""Regenerate every derived artefact from the registry + notes.

Idempotent: running it twice changes nothing the second time.

  * auto-blocks   <!-- cc:auto:NAME[:ARG] --> ... <!-- cc:end --> inside any note
  * Coverage.md   full status of the Atlas
  * Atlas.canvas  visual map: one group per domain, cards ordered by tier, coloured by status
  * Continuum Bridge.md   notes <-> the 35 practice projects
  * graph colours  .obsidian/graph.json colour groups per domain
"""
from __future__ import annotations

import json

from . import paths, registry, state
from .notes import iter_notes, replace_auto_blocks
from .util import bar, load_json, today, write_text

TIER_NAME = {1: "Foundational", 2: "Proficient", 3: "Advanced", 4: "Expert"}
STATUS_CANVAS_COLOR = {"planned": None, "stub": "3", "draft": "3", "revise": "1", "reviewed": "4", "evergreen": "6"}


# ----------------------------------------------------------------------------- generators
class Ctx:
    def __init__(self):
        self.topics = registry.load_topics()
        self.doms = registry.domains()
        self.by_dom: dict[str, list] = {}
        for t in self.topics:
            self.by_dom.setdefault(t.domain, []).append(t)


def gen_domain_index(ctx: Ctx, code: str | None) -> str:
    ts = ctx.by_dom.get(code or "", [])
    if not ts:
        return "_No topics registered for this domain._"
    lines = []
    for tier in (1, 2, 3, 4):
        group = [t for t in ts if t.tier == tier and t.type != "map"]
        if not group:
            continue
        lines.append(f"**Tier {tier} · {TIER_NAME[tier]}**")
        for t in group:
            lines.append(f"- {t.glyph} {t.link} · *{t.type}*")
        lines.append("")
    done = sum(1 for t in ts if t.status in registry.DONE)
    lines.append(f"`{bar(done / len(ts))}` {done}/{len(ts)} written · legend ○ planned ◐ draft ● reviewed ★ evergreen ⟲ revise")
    return "\n".join(lines)


def gen_home_domains(ctx: Ctx, _arg=None) -> str:
    rows = ["| | Domain | The question it answers | Progress |", "|---|---|---|---|"]
    for code, d in ctx.doms.items():
        ts = ctx.by_dom.get(code, [])
        if not ts:
            continue
        m = next((t for t in ts if t.type == "map"), None)
        name = m.link.replace("]]", f"\\|{d['name']}]]") if m else d["name"]
        done = sum(1 for t in ts if t.status in registry.DONE)
        rows.append(f"| `{code}` | {name} | {d['question']} | `{bar(done / len(ts), 8)}` {done}/{len(ts)} |")
    return "\n".join(rows)


def gen_home_stats(ctx: Ctx, _arg=None) -> str:
    c = registry.counts(ctx.topics)
    total = len(ctx.topics)
    written = sum(c[s] for s in registry.DONE)
    st = state.load()
    return "\n".join([
        "| Planned | Draft | Revise | Reviewed | Evergreen | Total | Builder runs | Editor runs |",
        "|---|---|---|---|---|---|---|---|",
        f"| {c['planned'] + c['stub']} | {c['draft']} | {c['revise']} | {c['reviewed']} | {c['evergreen']} | {total} | {st['builder_runs']} | {st['editor_runs']} |",
        "",
        f"`{bar(written / max(1, total), 20)}` **{written / max(1, total):.0%}** of the Atlas written · last build {today()}",
    ])


def gen_home_next(ctx: Ctx, _arg=None) -> str:
    cands = registry.candidates(ctx.topics, limit=6)
    if not cands:
        return "_Queue empty — the Editor should extend the registry._"
    return "\n".join(f"{i}. {t.link} · *{t.type}* · `{t.domain}` — {why}" for i, (t, why) in enumerate(cands, 1))


def gen_home_recent(ctx: Ctx, _arg=None) -> str:
    notes = [t for t in ctx.topics if t.note and t.status in registry.DONE]
    notes.sort(key=lambda t: (str(t.note.fm.get("updated") or ""), t.note.path.stat().st_mtime), reverse=True)
    if not notes:
        return "_Nothing written yet._"
    return "\n".join(f"- {t.glyph} {t.link} · *{t.type}* · updated {t.note.fm.get('updated', '?')}" for t in notes[:10])


GENERATORS = {
    "domain-index": gen_domain_index,
    "home-domains": gen_home_domains,
    "home-stats": gen_home_stats,
    "home-next": gen_home_next,
    "home-recent": gen_home_recent,
}


def refresh_auto_blocks(ctx: Ctx) -> list[str]:
    changed = []
    gens = {k: (lambda arg, f=f: f(ctx, arg)) for k, f in GENERATORS.items()}
    for p in iter_notes():
        text = p.read_text(encoding="utf-8").replace("\r\n", "\n")
        if "<!-- cc:auto:" not in text:
            continue
        new = replace_auto_blocks(text, gens)
        if write_text(p, new):
            changed.append(paths.rel(p))
    return changed


# ----------------------------------------------------------------------------- Coverage.md
def build_coverage(ctx: Ctx) -> bool:
    c = registry.counts(ctx.topics)
    total = len(ctx.topics)
    out = ["---", "type: system", "tags: [system/generated]", "---",
           "# Coverage", "",
           "> [!info] Generated by `cc.py build` — do not edit. The Atlas registry lives in `tools/data/topics.yaml`.", "",
           "| Status | Count |", "|---|---|"]
    for s in registry.STATUSES:
        out.append(f"| {registry.GLYPH[s]} {s} | {c.get(s, 0)} |")
    out += ["", f"**Total topics:** {total}", ""]
    for w in range(0, 5):
        ts = [t for t in ctx.topics if t.wave == w]
        if ts:
            done = sum(1 for t in ts if t.status in registry.DONE)
            out.append(f"- Wave {w}: `{bar(done / len(ts), 20)}` {done}/{len(ts)}")
    out.append("")
    for code, d in ctx.doms.items():
        ts = ctx.by_dom.get(code, [])
        if not ts:
            continue
        done = sum(1 for t in ts if t.status in registry.DONE)
        out += [f"## {code} · {d['name']}", "", f"*{d['question']}*  `{bar(done / len(ts))}` {done}/{len(ts)}", "",
                "| | Topic | Type | Tier | Wave | Score |", "|---|---|---|---|---|---|"]
        for t in ts:
            sc = t.note.fm.get("score", "") if t.note else ""
            out.append(f"| {t.glyph} | {t.link} | {t.type} | {t.tier} | {t.wave} | {sc} |")
        out.append("")
    return write_text(paths.COVERAGE, "\n".join(out) + "\n")


# ----------------------------------------------------------------------------- Atlas.canvas
def build_canvas(ctx: Ctx) -> bool:
    W, H, GAP, PAD, HEAD = 250, 56, 16, 30, 40
    COLS_PER_ROW = 4
    nodes, edges = [], []
    node_of: dict[str, str] = {}
    groups = []
    for code, d in ctx.doms.items():
        ts = [t for t in ctx.by_dom.get(code, []) if t.type != "map"]
        if not ts:
            continue
        cols = {tier: [t for t in ts if t.tier == tier] for tier in (1, 2, 3, 4)}
        cols = {k: v for k, v in cols.items() if v}
        gw = PAD * 2 + len(cols) * W + (len(cols) - 1) * GAP
        gh = PAD * 2 + HEAD + max(len(v) for v in cols.values()) * (H + GAP)
        groups.append((code, d, cols, gw, gh))
    x0 = y0 = 0
    row_h = 0
    for gi, (code, d, cols, gw, gh) in enumerate(groups):
        if gi and gi % COLS_PER_ROW == 0:
            x0, y0, row_h = 0, y0 + row_h + 120, 0
        m = next((t for t in ctx.by_dom[code] if t.type == "map"), None)
        nodes.append({"id": f"g-{code}", "type": "group", "x": x0, "y": y0, "width": gw, "height": gh,
                      "label": f"{code} · {d['name']}", "color": d["color"]})
        if m:
            nodes.append({"id": f"m-{code}", "type": "text", "x": x0 + PAD, "y": y0 + PAD - 6, "width": gw - 2 * PAD,
                          "height": HEAD - 4, "color": d["color"], "text": f"**{m.link}** {m.glyph}"})
        for ci, (tier, ts) in enumerate(cols.items()):
            for ri, t in enumerate(ts):
                nid = f"t-{t.id}"
                node_of[t.id] = nid
                node = {"id": nid, "type": "text", "x": x0 + PAD + ci * (W + GAP),
                        "y": y0 + PAD + HEAD + ri * (H + GAP), "width": W, "height": H,
                        "text": f"{t.glyph} {t.link}\n*{t.type} · T{t.tier}*"}
                col = STATUS_CANVAS_COLOR.get(t.status)
                if col:
                    node["color"] = col
                nodes.append(node)
        x0 += gw + 120
        row_h = max(row_h, gh)
    for t in ctx.topics:
        for p in t.pre:
            pt = next((x for x in ctx.topics if x.id == p), None)
            if pt and pt.domain == t.domain and p in node_of and t.id in node_of:
                edges.append({"id": f"e-{p}-{t.id}", "fromNode": node_of[p], "fromSide": "right",
                              "toNode": node_of[t.id], "toSide": "left"})
    data = {"nodes": nodes, "edges": edges}
    return write_text(paths.ATLAS_CANVAS, json.dumps(data, indent="\t", ensure_ascii=False) + "\n")


# ----------------------------------------------------------------------------- Continuum Bridge
def build_bridge(ctx: Ctx) -> bool:
    catalog = load_json(paths.CONTINUUM / "catalog.json", None)
    projects = []
    if catalog:
        for tier in catalog:
            for p in tier.get("projects", []):
                projects.append({"num": p["num"], "title": p["title"], "tier": tier.get("name", ""),
                                 "slug": f"{tier['slug']}/{p['slug']}"})
    by_num: dict[int, list] = {}
    for t in ctx.topics:
        nums = set(t.practice)
        if t.note:
            nums.update(int(x) for x in (t.note.fm.get("practice") or []) if str(x).isdigit())
        for n in nums:
            by_num.setdefault(int(n), []).append(t)
    out = ["---", "id: continuum-bridge", "type: system", "tags: [system/generated, practice]", "---",
           "# Continuum Bridge", "",
           "> [!essence] Knowledge becomes skill only through deliberate practice. This page joins every Compendium topic to the"
           " projects in the **CPP Project Continuum** (`__CLAUDE_ACA__/CPP_Project_Continuum`) that exercise it.", "",
           "> [!info] Generated by `cc.py build` from the registry (`pr:`) and note frontmatter (`practice:`).", ""]
    if not projects:
        out.append("_Continuum catalog not found next to the Compendium; showing registry links only._\n")
        projects = [{"num": n, "title": f"Project {n}", "tier": "", "slug": ""} for n in sorted(by_num)]
    tier = None
    for p in projects:
        if p["tier"] != tier:
            tier = p["tier"]
            out += ["", f"## {tier}" if tier else "## Projects", "", "| # | Project | Concepts it exercises |", "|---|---|---|"]
        ts = by_num.get(p["num"], [])
        links = ", ".join(f"{t.glyph} {t.link}" for t in ts) or "—"
        out.append(f"| {p['num']:02d} | {p['title']} | {links} |")
    return write_text(paths.BRIDGE, "\n".join(out) + "\n")


# ----------------------------------------------------------------------------- graph colours
def _hex_to_int(h: str) -> int:
    return int(h.lstrip("#"), 16)


def build_graph_colors(ctx: Ctx) -> bool:
    gp = paths.OBSIDIAN / "graph.json"
    if not gp.exists():
        return False
    g = json.loads(gp.read_text(encoding="utf-8"))
    groups = []
    for code, d in ctx.doms.items():
        folder = d["folder"]
        groups.append({"query": f'path:"{folder}"', "color": {"a": 1, "rgb": _hex_to_int(d["color"])}})
    groups.append({"query": 'path:"01 Maps"', "color": {"a": 1, "rgb": _hex_to_int("#f8fafc")}})
    if g.get("colorGroups") == groups:
        return False
    g["colorGroups"] = groups
    return write_text(gp, json.dumps(g, indent=2) + "\n")


# ----------------------------------------------------------------------------- entry
def build_all(verbose: bool = True) -> list[str]:
    ctx = Ctx()
    changed = refresh_auto_blocks(ctx)
    if build_coverage(ctx):
        changed.append(paths.rel(paths.COVERAGE))
    if build_canvas(ctx):
        changed.append(paths.rel(paths.ATLAS_CANVAS))
    if build_bridge(ctx):
        changed.append(paths.rel(paths.BRIDGE))
    if build_graph_colors(ctx):
        changed.append(".obsidian/graph.json")
    if verbose:
        print("build: " + (", ".join(changed) if changed else "no changes"))
    return changed
